# Generated by Django 5.0.6 on 2024-08-12 07:09

import django.core.validators
import ravi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ravi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='coapplicant_age',
            field=models.IntegerField(validators=[ravi.models.validate_age]),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='email_id',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='house_plot_purchase_value',
            field=models.CharField(default='', max_length=10, validators=[ravi.models.validate_amount]),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='ref1_mobile_number',
            field=models.CharField(default='', max_length=10, validators=[ravi.models.validate_mobile_number]),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='ref1_person_name',
            field=models.CharField(default='', max_length=200, validators=[ravi.models.validate_only_letters]),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='ref2_mobile_number',
            field=models.CharField(default='', max_length=200, validators=[ravi.models.validate_mobile_number]),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='ref2_person_name',
            field=models.CharField(default='', max_length=200, validators=[ravi.models.validate_only_letters]),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='required_loan_amount',
            field=models.CharField(default='', max_length=10, validators=[ravi.models.validate_amount]),
        ),
    ]
