# Generated by Django 5.0.6 on 2024-08-13 04:55

import ravi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ravi', '0002_alter_customerprofile_coapplicant_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantdocument',
            name='adhar_card_back',
            field=models.ImageField(default='', upload_to='documents/', validators=[ravi.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='applicantdocument',
            name='customer_photo',
            field=models.ImageField(default='', upload_to='documents/', validators=[ravi.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='applicantdocument',
            name='home_plot_photo_1',
            field=models.ImageField(default='', upload_to='documents/', validators=[ravi.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='applicantdocument',
            name='home_plot_photo_2',
            field=models.ImageField(default='', upload_to='documents/', validators=[ravi.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='applicantdocument',
            name='home_plot_photo_3',
            field=models.ImageField(default='', upload_to='documents/', validators=[ravi.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='applicantdocument',
            name='home_plot_photo_4',
            field=models.ImageField(default='', upload_to='documents/,', validators=[ravi.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='applicantdocument',
            name='pan_card',
            field=models.ImageField(default='', upload_to='documents/', validators=[ravi.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='email_id',
            field=models.EmailField(max_length=254, validators=[ravi.models.validate_email]),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='existing_loan_amount',
            field=models.CharField(default='', max_length=10, validators=[ravi.models.validate_amount]),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='existing_loan_bank_nbfc_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='plbasicdetailform',
            name='email',
            field=models.EmailField(max_length=254, validators=[ravi.models.validate_email]),
        ),
    ]
