# Generated by Django 5.0.6 on 2024-08-13 05:05

import ravi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ravi', '0003_alter_applicantdocument_adhar_card_back_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantdocument',
            name='existing_loan_statement',
            field=models.FileField(default='', upload_to='documents/', validators=[ravi.models.validate_pdf_file]),
        ),
        migrations.AlterField(
            model_name='applicantdocument',
            name='other_documents_1',
            field=models.FileField(default='', upload_to='documents/', validators=[ravi.models.validate_pdf_file]),
        ),
        migrations.AlterField(
            model_name='applicantdocument',
            name='other_documents_2',
            field=models.FileField(default='', upload_to='documents/', validators=[ravi.models.validate_pdf_file]),
        ),
        migrations.AlterField(
            model_name='applicantdocument',
            name='other_documents_3',
            field=models.FileField(default='', upload_to='documents/', validators=[ravi.models.validate_pdf_file]),
        ),
        migrations.AlterField(
            model_name='applicantdocument',
            name='other_documents_4',
            field=models.FileField(default='', upload_to='documents/', validators=[ravi.models.validate_pdf_file]),
        ),
    ]
